apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wat
  name: wat
  labels:
    app: wat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wat
  template:
    metadata:
      labels:
        app: wat
    spec:
      containers:
      - name: wat-instance
        image: harbor.peciak.xyz/mpeciak/wat:main
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: harbor-registry-secret
            